name: styfi
plugins:
  - name: vyper
  - name: foundry
  - name: etherscan
vyper:
  evm_version: cancun
ethereum:
  default_network: local
  local:
    default_provider: foundry
  mainnet_fork:
    default_provider: foundry
